travis:
  secure:
    BINSTAR_TOKEN: D8D6HpXxNg3v8Kii7g7Ktu7dxYpnjQwxG07r6/t/HlL+uNSgLY4ukUc6v8couA/5D1RGDfV5BwM9axjNg/YbO7tYSK3KyQDkTVlsuE4KdpRdG5Q+YM/jwMReOvXdEQScSYkDevzlhTbip6bHRtVwG3Osi3sUmTsKwZ4kKRs0jb4BimooXIjJiGxVjjoggdX4Cc58IU6XUUgIKIbJJykPRw3sh/lxL6fGhI2Fi06rKC1NHLJIpkP7eMACQOL10vIz98xowyEKRaZcx07Spw0lHQ16XvL6rNuWoupcBXDfx+0BZ4W2G7Q67ftFWQWOPqIrQd1d2GWNx2vuKynwbqe1shpPFUoCapz/AgKOvnYdNpclDzXfEPbtNmdqAgQdzWLI+Chs/OrdrQQtfBzUf2jLTgpvJEiYYdtZgC56djURVP1PYWS+6eOSIiusPFsyKmF7qCKKlGw3bLvnOFAqLpTeYvOm3K4e47QMA/vwCsABnfGMY7gXtGW47ixKKxVVryPtMDcX+szfUIDMrvNTGBV/nHK2NQwa4tu8Rev2+dfZhLVu6ZKjbuN5gyKa/GEIZ9mHx+hHcLxJ+uDTH6nzWEqG90iYgVLRQoijpdKHh2RSU/yi4cIvWOrRJRIGRsXrJmi8ZMQNs0Hn0Ygx/hS6/vUNSUx5H5L57nU3yeE3lNdyB6k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
